### ISSUE TITLE
IMP test

### ISSUE THREAD

**Issue by shruthivis** [isblab/nestor#21]
Inherit from https://github.com/salilab/imp-sampcon/blob/main/test/medium_test_exhaust.py 

1. Check that python module is runnable
2. Check that output files are present 
3. Check that evidences for each rep., we obtain are reasonable compared to a previous run of 3 replicates (10% of the mean, within 1 std error).

**Comment by shruthivis** [comment]
1. make it in the style of an iMP module. `pyext/src` having nester_macro.py, wrapper.py, xl_datasplitter.py, compare_runs. 
2. pull the tests specific to nestor to the `test` dir. 
3. dependencies.py: see dependencies of PMI. 
4. Make sure that  nested sampling macro works as a separate file. 
5. Put tests in nestor/test dir 
6. Current example can be in `examples`, along with its README. 
7. copy all other files from sampcon

**Comment by shruthivis** [comment]
https://github.com/isblab/pmi/blob/f8d982281bacccc81f5f6aab36699215051bc7ac/test/test_nested_sampling.py#L155 fix to setup setB. 

https://github.com/isblab/pmi/blob/f8d982281bacccc81f5f6aab36699215051bc7ac/test/test_nested_sampling.py#L126C14-L126C80 change path name 

Add tests for module runnability 

Add tests for presence of output files

**Comment by shruthivis** [comment]
remove user specific dir names in test scripts and in yaml script. Assume tests are run from the test dir.

**Comment by shruthivis** [comment]
FileNotFoundError: [Errno 2] No such file or directory: '~/cgimp/imp/modules/nestor/test/runs/'

**Comment by shruthivis** [comment]
make tests as light as possible: 3 replicates, rep5 instead of 10, etc.

**Comment by shreyas-arvindekar** [comment]
> remove user specific dir names in test scripts and in yaml script. Assume tests are run from the test dir. `test_that_works.py` , `modeling_testcase.py`, `nestor_params_optrep.yaml`

Which file is this issue for?

**Comment by shreyas-arvindekar** [comment]
> make tests as light as possible: 3 replicates, rep5 instead of 10, etc.

Done. See [da7f7e7](https://github.com/isblab/nestor/commit/da7f7e718486fed2ea7fe6af599a9c0d791dd662)

**Comment by shruthivis** [comment]
> > remove user specific dir names in test scripts and in yaml script. Assume tests are run from the test dir. `test_that_works.py` , `modeling_testcase.py`, `nestor_params_optrep.yaml`
> 
> Which file is this issue for?

grep `shreyas` in all the above files and replace hardcoded paths in tests. E.g. 
dat_dir = "/home/shreyas/Projects/cgopt/imp_integration_stuff/cgimp/imp/modules/nestor/test/input/" in `https://github.com/isblab/nestor/blob/imp-integration/test/modeling_testcase.py` 

use relative paths based on test dir

**Comment by shruthivis** [comment]
Remove these test functions: wrapper_test, test_self_consistency, testing of file outputs can be in the same test function as test_reproduci* 
Resolution = 10 alone.
