### ISSUE TITLE
merge wrapper and plot_proctime_and_evidence together

### ISSUE THREAD

**Issue by shruthivis** [isblab/nestor#23]
Update readme and example in nestor dir accordingly

**Comment by shreyas-arvindekar** [comment]
Done. See [fad6051](https://github.com/isblab/nestor/commit/fad605166ee8a89a8a4fe182d6663810aa8c358e)

**Comment by shruthivis** [comment]
1. delete the plot_proctime*py file? 
2. Update the README run command point 2 to use wrapper with skip plotting
3. Also update README in `imp-integration/examples` to remove reference to plotting script and instead reference the wrapper with the skip option.
