### ISSUE TITLE
test_nested_sampling error in test_reproducibility

### ISSUE THREAD

**Issue by shruthivis** [isblab/nestor#27]
OSError: UsageError: "This file is currently being written to. Close it first."

Fix RMF file close error in macro.

Add RMF file close command. 
Use subprocess. 
Or fix the PMI macros change that caused this.

**Comment by shreyas-arvindekar** [comment]
Fixed. PR accepted in PMI repo. See [26c9da6](https://github.com/salilab/pmi/commit/26c9da6a01b10318c9c4ed97ee1aebd57dc4a4e0)
